users: 60
duration: 60 # in seconds
requests:
  GET:
    - endpoint: http://localhost:3000/jobs
    - endpoint: http://localhost:3000/job/1
  POST:
    - endpoint: http://localhost:3000/locations/add_locations
      body: {"location": "Australia"}
    - endpoint: http://localhost:3000/jobs/1/edit_job
      body: {"pay": 10000}